# Generated by Django 4.0.6 on 2022-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=200)),
                ('ranking', models.IntegerField()),
            ],
        ),
    ]
